In [227]:
# from:
# https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md

In [2]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [3]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
y = np.round(np.log(x), 3)
y

array([0.   , 0.693, 1.099, 1.386, 1.609, 1.792, 1.946, 2.079, 2.197])

In [11]:
print(x[1:] - x[0:-1])
y_diff = y[1:] - y[0:-1]
print(y_diff)

[1 1 1 1 1 1 1 1]
[0.69315 0.40546 0.28768 0.22315 0.18232 0.15415 0.13353 0.11778]


In [12]:
print(2**3, 2**3.1)
print(2**8, 2**8.1)

8 8.574187700290345
256 274.374006409291


In [5]:
#### 2. Print the numpy version and the configuration (★☆☆)
print(np.__version__)
print(np.show_config())

1.23.2
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/homebrew/opt/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/homebrew/opt/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/homebrew/opt/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/homebrew/opt/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = ASIMDHP,ASIMDDP
    not found = ASIMD

In [7]:
#### 3. Create a null vector of size 10 (★☆☆)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
#### 4. How to find the memory size of any array (★☆☆)
print(np.zeros(10).size) # how many items are in the array (shape multiplication)
print(np.zeros(10).itemsize) # we are using 8 byte (32 bit) integers
print(np.zeros(10, dtype=float).itemsize) # floats are 32 bit too...

10
8
8


In [25]:
#### 5. How to get the documentation of the numpy add function
print(help(np.add))
# or 
# np.info(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [26]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [27]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
np.arange(10, 50, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [29]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
np.arange(10, 50, 1)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [33]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
np.random.randint(8, size=(3,3))

# much better... create the values in 1d and reshape to whatever shape we want
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
# VERY GOOD FUNCTION FOR NONZERO what about NONNAN 
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [40]:
np.nonzero([1,2,np.nan,0,4,0])

(array([0, 1, 2, 4]),)

In [62]:
# this just needed to literally be a numpy array for boolean indexing
x = np.array([1,2,np.nan,0,4,0])
print(~np.isnan(x))
x[~np.isnan(x)]

[ True  True False  True  True  True]


array([1., 2., 0., 4., 0.])

In [63]:
print(np.arange(7) > 4)
np.arange(7)[np.arange(7) > 4]

[False False False False False  True  True]


array([5, 6])

In [65]:
#### 11. Create a 3x3 identity matrix (★☆☆)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
np.random.random((3,3,3))

array([[[0.24726809, 0.90776054, 0.48747853],
        [0.8287777 , 0.54272883, 0.45497482],
        [0.97324734, 0.97188022, 0.56847361]],

       [[0.59605909, 0.25282375, 0.39234551],
        [0.21896289, 0.0683348 , 0.55479126],
        [0.28342071, 0.27506646, 0.76340237]],

       [[0.29349183, 0.46113447, 0.41302263],
        [0.46785253, 0.27282286, 0.87602656],
        [0.7107623 , 0.5177189 , 0.94782862]]])

In [72]:
#### 13. Create a 10x10 array with random values and find the min and max vals
nd = np.random.random((10,10))
nd.max()
nd.min()

# or
np.max(nd)
np.min(nd)

0.0021540083815826394

In [73]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
a = np.random.random(30)
a.mean()

0.5134125749442594

In [74]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [76]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
# get the shape, create a new array with shape + 1 for each variable, then init
# np.ones and do the same thing to set the inside as the original data

# np.pad is the function to use to add values around an array
a = np.ones((5,5))
np.pad(a, pad_width=1)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#### 17. What is the result of the following expression? (★☆☆)
"""
0 * np.nan ... nan
np.nan == np.nan ... true WRONG: FALSE
np.inf > np.nan ... false
np.nan - np.nan ... 0... WRONG: np.nan
np.nan in set([np.nan]) ... false WRONG: FALSE
0.3 == 3 * 0. false
"""

In [86]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.)

nan
False
False
nan
True
False


In [91]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
np.diag(1+np.arange(4), k=-1)

# set the values along the diagonal... k is the offset... we could add one to do
# above the diag
np.diag(1+np.arange(4), k=1)

# seems like np.diag takes an ndarray... k is the "diagonal in question"

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [98]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
a = np.ones((8,8))
a[::2, ::2] = 0
a[1::2, 1::2] = 0
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [104]:
#### 20. Consider a (6,7,8) shape array, what is index (x,y,z) of the 100th element
np.unravel_index(99,(6,7,8))

# unravel index basically means map a one dimensional idx to a ndimensional idx

(1, 5, 3)

In [111]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
tile = np.array([[0, 1],[1, 0]])
np.tile(tile, (4,4))

# np.tile basically takes an np array and then duplicates it, so the 
# array that you use is the "tile"

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [117]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
a = np.random.random((5,5))

# or manually calculate
(a - a.mean()) / a.std()

array([[-2.15652285,  1.13381699, -0.25554804,  1.54026654,  1.34704905],
       [ 0.63853732,  0.90697324,  0.11481086,  0.17554058,  0.47623615],
       [-0.80273519, -0.87767732, -0.98244224, -1.67005432,  1.44449766],
       [ 1.08935387, -1.04810086,  0.00991972,  0.42210145, -1.07512146],
       [ 0.51107192,  0.46100512,  0.21045321, -0.25175067, -1.36168074]])

In [120]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([
    ("r", np.ubyte),
    ("g", np.ubyte),
    ("b", np.ubyte),
    ("a", np.ubyte),
])
color

# it is pretty cool that we can create our own primitive data types easily

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [122]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
np.random.random((5,3)).dot(np.random.random((3,2)))

array([[1.02204471, 0.72243043],
       [1.05838621, 0.71307903],
       [1.78241076, 1.22038419],
       [0.89657069, 0.48918268],
       [1.67156819, 1.13632793]])

In [124]:
# interesting... the @ is a new symbol for matrix (dot) multiplication
np.random.random((5,3)) @ np.random.random((3,2))

array([[0.67289899, 1.82685042],
       [0.25813017, 1.033854  ],
       [0.25158861, 1.25352215],
       [0.21432438, 0.52513962],
       [0.19968121, 1.26379231]])

In [128]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place
a = np.arange(10)
np.where((a > 2) & (a < 9), -a, a)

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

In [131]:
#### 26. What is the output of the following script? (★☆☆)
"""
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
"""

'\nprint(sum(range(5),-1))\nfrom numpy import *\nprint(sum(range(5),-1))\n'

In [133]:
print(sum(range(5),-1))
# sum(iterable, start), -1 means sum 4 and 5

# the -1 refers to axis in numpy

9


In [134]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
"""
Z**Z
2 << Z >> 2
Z <- Z 
1j*Z
Z/1/1
Z<Z>Z
"""

'\nZ**Z\n2 << Z >> 2\nZ <- Z \n1j*Z\nZ/1/1\nZ<Z>Z\n'

In [139]:
# min, max, size
a = np.random.randint(1, 5, size=(4, 4))
a

array([[1, 2, 2, 2],
       [2, 2, 3, 3],
       [1, 1, 4, 3],
       [2, 4, 2, 4]])

In [141]:
a**a #valid

array([[  1,   4,   4,   4],
       [  4,   4,  27,  27],
       [  1,   1, 256,  27],
       [  4, 256,   4, 256]])

In [142]:
# bit shifting
2 << a >> 2

array([[1, 2, 2, 2],
       [2, 2, 4, 4],
       [1, 1, 8, 4],
       [2, 8, 2, 8]])

In [143]:
# boolean indexing
a < -a

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [144]:
# a complex number
1j*a

array([[0.+1.j, 0.+2.j, 0.+2.j, 0.+2.j],
       [0.+2.j, 0.+2.j, 0.+3.j, 0.+3.j],
       [0.+1.j, 0.+1.j, 0.+4.j, 0.+3.j],
       [0.+2.j, 0.+4.j, 0.+2.j, 0.+4.j]])

In [145]:
a/1/1

array([[1., 2., 2., 2.],
       [2., 2., 3., 3.],
       [1., 1., 4., 3.],
       [2., 4., 2., 4.]])

In [147]:
# a<a>a # NOT POSSIBLE

In [148]:
#### 28. What are the result of the following expressions? (★☆☆)
"""
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
"""

'\nnp.array(0) / np.array(0)\nnp.array(0) // np.array(0)\nnp.array([np.nan]).astype(int).astype(float)\n'

In [149]:
np.array(0) / np.array(0)

/var/folders/_m/r4y9hlzx625650fwyg4glc0m0000gp/T/ipykernel_67041/873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [150]:
np.array(0) // np.array(0)

/var/folders/_m/r4y9hlzx625650fwyg4glc0m0000gp/T/ipykernel_67041/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [152]:
# nan is a float, and when we go from nan to int I guess we go to zero
np.array([np.nan]).astype(int).astype(float)

array([0.])

In [153]:
#### 30. How to find common values between two arrays? (★☆☆)
np.intersect1d(np.random.randint(0,10,10), np.random.randint(0,10,10))

array([1, 4, 5, 6, 7, 8])

In [154]:
#### 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/_m/r4y9hlzx625650fwyg4glc0m0000gp/T/ipykernel_67041/306841201.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [158]:
# print(type(np.sqrt(-1))) # THIS IS A FLOAT, not a COMPLEX number
print(type(np.emath.sqrt(-1)))

<class 'numpy.complex128'>


In [159]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [160]:
today

numpy.datetime64('2022-08-29')

In [163]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

# very interesting that numpy has its own built in calendar... we should use that
# instead of generating our calendar on our own... we probably do and then
# filter for weekends and holidays and remove that from the list

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [165]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

# we can use the `out` keyword to say do not return a copy but rather write this
# to the memory of A or B

array([-1.5, -1.5, -1.5])

In [167]:
#### 36. Extract the integer part of a random array of positive numbers 4 dif ways
np.random.random((5,5)).astype(int)
print(np.random.random((5,5)) // 1)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [168]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
np.random.randint(0, 4, size=(5,5))

array([[2, 0, 3, 3, 3],
       [0, 1, 2, 2, 2],
       [1, 3, 0, 0, 2],
       [2, 3, 0, 0, 2],
       [2, 3, 1, 3, 2]])

In [171]:
np.tile(np.arange(5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [172]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generator():
    for x in range(10):
        yield x
np.array(list(generator()))


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
def generator():
    for x in range(10):
        yield x

# very similar to wrapping, I guess from iterator is better though
np.fromiter(generator(), dtype=int)

# the generator is actually an iterable... it just generates an iterator
# and then calls next on that iterator

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [186]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
a = np.random.random(10)
a.sort() # this sorts in place
a

array([0.03316727, 0.03459606, 0.14829642, 0.15446323, 0.42584868,
       0.44774218, 0.46236389, 0.78301283, 0.81996853, 0.96942593])

In [189]:
#### 42. Consider two random array A and B, check if they are equal (★★☆)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.all(A == B)

False

In [190]:
A

array([1, 0, 1, 1, 1])

In [191]:
B

array([0, 0, 0, 1, 1])

In [192]:
np.allclose(A,B)

False

In [193]:
np.array_equal(A,B)

False

In [196]:
#### 43. Make an array immutable (read-only) (★★☆)
a = np.ones(10)
a.flags.writeable = False

# interesting way to make something const

In [198]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
a = np.random.random((10,2))

# Cartesian (x,y) -> Polar (r, theta)
# r = sqrt(x^2 + y^2), theta = inverse tan (x/y)
R = np.sqrt(a[:,0] ** 2 + a[:,1] ** 2)
T = np.arctan(a[:,0]/a[:,1])
print(R)
print(T)


[0.6831375  1.14849762 0.81146669 1.07580496 0.73911277 1.02621762
 0.73463895 0.77363241 0.37032514 1.28867095]
[1.26564666 0.75318968 0.91288572 0.62827543 0.56530669 0.78609305
 0.96943263 0.67183739 0.38966065 0.74141031]


In [207]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
# start stop size
a = np.random.randint(0, 10, 10)
a[np.argmax(a)] = 0
a

# or just a.argmax()

array([0, 2, 1, 1, 0, 6, 1, 6, 4, 0])

In [208]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C
# (Cij =1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [209]:
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [213]:
np.zeros(10, [ ('position', [ ('x', float, int),
                                  ('y', float, int)]),
                   ('color',    [ ('r', float, int),
                                  ('g', float, int),
                                  ('b', float, int)])])

# I should read more about structured numpy arrays, they are
# what our dictionaries are at peri

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [219]:
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
a = np.random.random((100,2))

import scipy 
spatial.distance.cdist(a,a)

ModuleNotFoundError: No module named 'scipy'

In [221]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
D

array([[0.        , 0.38912087, 0.95871301, 0.80471105, 0.6117706 ,
        1.09095578, 0.32553757, 0.82530863, 0.27499587, 0.88288407],
       [0.38912087, 0.        , 0.65793839, 0.53254433, 0.30374085,
        0.7706082 , 0.1823656 , 0.79587677, 0.54371076, 0.84596355],
       [0.95871301, 0.65793839, 0.        , 0.16229445, 0.35874548,
        0.14273346, 0.63408993, 0.63231314, 0.93799668, 0.64083898],
       [0.80471105, 0.53254433, 0.16229445, 0.        , 0.22957691,
        0.30448372, 0.48304121, 0.5218745 , 0.7757031 , 0.54229386],
       [0.6117706 , 0.30374085, 0.35874548, 0.22957691, 0.        ,
        0.48227388, 0.28741248, 0.61080412, 0.64508961, 0.64894036],
       [1.09095578, 0.7706082 , 0.14273346, 0.30448372, 0.48227388,
        0.        , 0.76543467, 0.7541675 , 1.0797981 , 0.75612646],
       [0.32553757, 0.1823656 , 0.63408993, 0.48304121, 0.28741248,
        0.76543467, 0.        , 0.63369641, 0.39152589, 0.68677775],
       [0.82530863, 0.79587677, 0.6323131

In [222]:
#### 56. Generate a generic 2D Gaussian-like array (★★☆)
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [223]:
#### 58. Subtract the mean of each row of a matrix (★★☆)
X = np.random.rand(5, 10)
Y = X - X.mean(axis=0)
Y

array([[ 0.17948116, -0.36738373, -0.45383639,  0.25813691, -0.49438802,
         0.19255413, -0.1298473 , -0.25715058, -0.43272827,  0.22173634],
       [ 0.4170452 , -0.31357152,  0.26671065, -0.02550615, -0.33099375,
         0.13408985, -0.15316071, -0.17123856,  0.39647226,  0.21570031],
       [ 0.15063956,  0.37008437,  0.39458816,  0.40285911, -0.45679442,
        -0.45444923, -0.38146711, -0.07812818,  0.37675894, -0.46328998],
       [ 0.43803422,  0.15156283, -0.16145007,  0.36493472, -0.22095119,
        -0.3449055 , -0.18266589,  0.3077878 , -0.41254638,  0.28316911],
       [ 0.44000336,  0.15464616,  0.22190197,  0.41216991,  0.25080255,
         0.12498864, -0.22417521, -0.04160582, -0.43081962, -0.14380462]])

In [224]:
#### 59. How to sort an array by the nth column? (★★☆)
# this is like `conjoined vectors`
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 6 6]
 [6 5 5]
 [4 8 0]]
[[6 5 5]
 [7 6 6]
 [4 8 0]]


In [225]:
#### 63. Create an array class that has a name attribute (★★☆)
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [228]:
#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [229]:
#### 75. How to compute averages using a sliding window over an array? (★★★)
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [231]:
#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
from numpy.lib import stride_tricks

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 4 2]
   [4 1 0]
   [1 4 1]]

  [[4 2 3]
   [1 0 4]
   [4 1 2]]

  [[2 3 4]
   [0 4 4]
   [1 2 1]]

  [[3 4 1]
   [4 4 4]
   [2 1 2]]

  [[4 1 2]
   [4 4 4]
   [1 2 4]]

  [[1 2 0]
   [4 4 1]
   [2 4 3]]

  [[2 0 1]
   [4 1 3]
   [4 3 0]]

  [[0 1 4]
   [1 3 3]
   [3 0 2]]]


 [[[4 1 0]
   [1 4 1]
   [4 3 4]]

  [[1 0 4]
   [4 1 2]
   [3 4 2]]

  [[0 4 4]
   [1 2 1]
   [4 2 4]]

  [[4 4 4]
   [2 1 2]
   [2 4 4]]

  [[4 4 4]
   [1 2 4]
   [4 4 1]]

  [[4 4 1]
   [2 4 3]
   [4 1 0]]

  [[4 1 3]
   [4 3 0]
   [1 0 3]]

  [[1 3 3]
   [3 0 2]
   [0 3 4]]]


 [[[1 4 1]
   [4 3 4]
   [3 3 1]]

  [[4 1 2]
   [3 4 2]
   [3 1 1]]

  [[1 2 1]
   [4 2 4]
   [1 1 1]]

  [[2 1 2]
   [2 4 4]
   [1 1 0]]

  [[1 2 4]
   [4 4 1]
   [1 0 0]]

  [[2 4 3]
   [4 1 0]
   [0 0 3]]

  [[4 3 0]
   [1 0 3]
   [0 3 1]]

  [[3 0 2]
   [0 3 4]
   [3 1 2]]]


 [[[4 3 4]
   [3 3 1]
   [4 1 0]]

  [[3 4 2]
   [3 1 1]
   [1 0 1]]

  [[4 2 4]
   [1 1 1]
   [0 1 3]]

  [[2 4 4]
   [1 1 0]
   [1 3 4]]

  [[4 4 1]
   

In [232]:
#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.0526576   0.33748339]


In [233]:
# https://codesolid.com/numpy-practice-questions-to-make-you-an-expert/

In [234]:
np.arange(10, 101, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [237]:
np.array(list(range(10, 101, 10)))

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [239]:
np.array([])

array([], dtype=float64)

In [240]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [241]:
np.zeros(10).dtype

dtype('float64')

In [242]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [244]:
np.random.randint(1, 6, size=(10))

array([1, 2, 2, 4, 1, 4, 4, 5, 4, 3])

In [249]:
np.random.normal(5, 1, size=10)

array([5.88073868, 6.95136762, 4.77798286, 3.98782501, 5.17892018,
       2.92360922, 5.16340774, 5.98950406, 5.41287227, 4.42685822])

In [250]:
np.random.random((10))

array([0.07792712, 0.34109391, 0.82197184, 0.55643867, 0.67474359,
       0.35219041, 0.2054187 , 0.21749654, 0.22059225, 0.41421227])

In [251]:
np.random.rand((10))

array([0.48145187, 0.49396913, 0.27460776, 0.97661033, 0.09095617,
       0.25018186, 0.04796971, 0.41294137, 0.65269706, 0.11907916])